version: "3"

services:
  # SPECIES SERVICES
  species:
    container_name: species
    build: ./species
    restart: always
    env_file: ./species/.env
    ports:
      - "5001:5001"
    depends_on:
      - species_db

  species_db:
    image: mongo
    container_name: species_db
    restart: always
    env_file: ./species/.env
    ports:
      - "36015:27017"
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    logging:
      driver: none

  # TREES SERVICES
  trees:
    container_name: trees
    build: ./trees
    restart: always
    env_file: ./trees/.env
    ports:
      - "5002:5002"
    depends_on:
      - trees_db

  trees_db:
    image: mongo
    container_name: trees_db
    restart: always
    env_file: ./trees/.env
    ports:
      - "36016:27017"
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    logging:
      driver: none

  # GROVES SERVICES
  groves:
    container_name: groves
    build: ./groves
    restart: always
    env_file: ./groves/.env
    ports:
      - "5003:5003"
    depends_on:
      - groves_db

  groves_db:
    image: mongo
    container_name: groves_db
    restart: always
    env_file: ./groves/.env
    ports:
      - "36017:27017"
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    logging:
      driver: none

  # HARVESTS SERVICES
  harvests:
    container_name: harvests
    build: ./harvests
    restart: always
    env_file: ./harvests/.env
    ports:
      - "5004:5004"
    depends_on:
      - harvests_db

  harvests_db:
    image: mongo
    container_name: harvests_db
    restart: always
    env_file: ./harvests/.env
    ports:
      - "36018:27017"
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    logging:
      driver: none